DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTO_INCREMENT ,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTO_INCREMENT ,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR(255) NOT NULL,
  body VARCHAR(255) NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE config (
  id INTEGER PRIMARY KEY AUTO_INCREMENT ,
  user_id INTEGER NOT NULL,
  account_mt5 INTEGER NOT NULL,
  server_mt5 VARCHAR(255) NOT NULL,
  password_mt5 VARCHAR(255) NOT NULL,
  symbol VARCHAR(255) NOT NULL,
  periodic VARCHAR(255) NOT NULL,
  status INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user (id)
);
